# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.79
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ReplySettingsWithVerifiedUsers(str, Enum):
    """
    Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, subscribers, verified and following.
    """

    """
    allowed enum values
    """
    EVERYONE = 'everyone'
    MENTIONEDUSERS = 'mentionedUsers'
    FOLLOWING = 'following'
    OTHER = 'other'
    SUBSCRIBERS = 'subscribers'
    VERIFIED = 'verified'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReplySettingsWithVerifiedUsers from a JSON string"""
        return cls(json.loads(json_str))


