# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.79
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.general_api import GeneralApi


class TestGeneralApi(unittest.TestCase):
    """GeneralApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GeneralApi()

    def tearDown(self) -> None:
        pass

    def test_get_open_api_spec(self) -> None:
        """Test case for get_open_api_spec

        Returns the OpenAPI Specification document.
        """
        pass

    def test_get_rule_count(self) -> None:
        """Test case for get_rule_count

        Rules Count
        """
        pass


if __name__ == '__main__':
    unittest.main()
