# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.79
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.reply_settings_with_verified_users import ReplySettingsWithVerifiedUsers

class TestReplySettingsWithVerifiedUsers(unittest.TestCase):
    """ReplySettingsWithVerifiedUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplySettingsWithVerifiedUsers(self):
        """Test ReplySettingsWithVerifiedUsers"""
        # inst = ReplySettingsWithVerifiedUsers()

if __name__ == '__main__':
    unittest.main()
