# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.79
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.usage_daily_project_usage import UsageDailyProjectUsage

class TestUsageDailyProjectUsage(unittest.TestCase):
    """UsageDailyProjectUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageDailyProjectUsage:
        """Test UsageDailyProjectUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageDailyProjectUsage`
        """
        model = UsageDailyProjectUsage()
        if include_optional:
            return UsageDailyProjectUsage(
                project_id = 56,
                usage = [
                    openapi_client.models.usage_fields.UsageFields(
                        date = '2021-01-06T18:40:40Z', )
                    ]
            )
        else:
            return UsageDailyProjectUsage(
        )
        """

    def testUsageDailyProjectUsage(self):
        """Test UsageDailyProjectUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
