# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.79
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from openapi_client.models.create_attachments_message_request import CreateAttachmentsMessageRequest
from openapi_client.models.create_text_message_request import CreateTextMessageRequest
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

CREATEMESSAGEREQUEST_ANY_OF_SCHEMAS = ["CreateAttachmentsMessageRequest", "CreateTextMessageRequest"]

class CreateMessageRequest(BaseModel):
    """
    CreateMessageRequest
    """

    # data type: CreateTextMessageRequest
    anyof_schema_1_validator: Optional[CreateTextMessageRequest] = None
    # data type: CreateAttachmentsMessageRequest
    anyof_schema_2_validator: Optional[CreateAttachmentsMessageRequest] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CreateAttachmentsMessageRequest, CreateTextMessageRequest]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: List[str] = Literal[CREATEMESSAGEREQUEST_ANY_OF_SCHEMAS]

    model_config = {
        "validate_assignment": True
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = CreateMessageRequest.model_construct()
        error_messages = []
        # validate data type: CreateTextMessageRequest
        if not isinstance(v, CreateTextMessageRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateTextMessageRequest`")
        else:
            return v

        # validate data type: CreateAttachmentsMessageRequest
        if not isinstance(v, CreateAttachmentsMessageRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateAttachmentsMessageRequest`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in CreateMessageRequest with anyOf schemas: CreateAttachmentsMessageRequest, CreateTextMessageRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[CreateTextMessageRequest] = None
        try:
            instance.actual_instance = CreateTextMessageRequest.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CreateAttachmentsMessageRequest] = None
        try:
            instance.actual_instance = CreateAttachmentsMessageRequest.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateMessageRequest with anyOf schemas: CreateAttachmentsMessageRequest, CreateTextMessageRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            return json.dumps(self.actual_instance)

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


